#pragma once

namespace expresso {

namespace core {

// Scrapped from [Mozilla status code
// documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#server_error_responses)
// and [Wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
enum StatusCode {
  // Informational responses
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  EARLY_HINTS = 103,

  // Successful responses
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTEXT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  ALREADY_REPORTED = 208,
  THIS_IS_FINE = 218,
  IM_USED = 226,

  // Redirectional messages
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  UNUSED = 306,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,

  // Client error responses
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXT_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  IM_A_TEAPOT = 418,
  PAGE_EXPIRED = 419,
  METHOD_FAILURE = 420,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_CONTENT = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  TOO_EARLY = 425,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELD_TOO_LARGE = 431,
  LOGIN_TIMEOUT = 440,
  NO_RESPONSE = 444,
  RETRY_WITH = 449,
  BLOCKED_BY_PARENTAL_CONTROL = 450,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,
  REQUEST_HEADER_TOO_LARGE = 494,
  SSL_CERTIFICATE_ERROR = 495,
  SSL_CERTIFICATE_REQUIRED = 496,
  HTTP_REQUEST_SENT_TO_HTTPS_PORT = 497,
  INVALID_TOKEN = 498,
  TOKEN_REQUIRED = 499,

  // Server error responses
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  VARIANT_ALSO_NEGOTIATES = 506,
  INSUFFICIENT_STORAGE = 507,
  LOOP_DETECTED = 508,
  BANDWIDTH_LIMIT_EXCEEDED = 509,
  NOT_EXTENDED = 510,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
  WEB_SERVER_RETURNED_AN_UNKNOWN_ERROR = 520,
  WEB_SERVER_IS_DOWN = 521,
  CONNECTION_TIMED_OUT = 522,
  ORIGIN_IS_UNREACHABLE = 523,
  A_TIMEOUT_OCCURED = 524,
  SSL_HANDSHAKE_FAILED = 525,
  INVALID_SSL_CERTIFICATE = 526,
  RAILGUN_ERROR = 527,
  SITE_IS_OVERLOADED = 529,
  SITE_IS_FROZEN = 530,
  NETWORK_READ_TIMEOUT_ERROR = 598,
  NETWORK_CONNECT_TIMEOUT_ERROR = 599
};

} // namespace core

} // namespace expresso